### ISSUE TITLE
xml parsing error occurred trying to get md5 data for ....

### ISSUE THREAD

**Issue by sairuk** [eddie3/gogrepo#63] opened 2022-02-24 19:10 UTC
Looks like gog may have changed something recently. We have received and confirmed reports (as per https://github.com/danmons/retronas/issues/117) of our users getting xml parsing errors during manifest refresh from this tool.

```
Refreshing GOG manifest...

06:07:32 | loading local manifest...
06:07:32 | fetching game product data (page 1)...
06:07:33 | fetching game product data (page 2 / 3)...
06:07:33 | fetching game product data (page 3 / 3)...
06:07:34 | (  1 / 255) fetching game details for a_space_for_the_unbound_prologue...
06:07:41 | xml parsing error occurred trying to get md5 data for setup_a_space_for_the_unbound_-_prologue_v8.54g_(45722).exe
06:07:41 | (  2 / 255) fetching game details for absolute_drift...
06:07:48 | xml parsing error occurred trying to get md5 data for setup_absolute_drift_1.0g_(64bit)_(49142).exe
06:07:48 | (  3 / 255) fetching game details for against_the_moon_prologue...
06:07:54 | xml parsing error occurred trying to get md5 data for setup_against_the_moon_prologue_129_(42110).exe
06:07:54 | (  4 / 255) fetching game details for akalabeth_world_of_doom...
06:08:00 | xml parsing error occurred trying to get md5 data for setup_akalabeth_2.0.0.1.exe
06:08:09 | (  5 / 255) fetching game details for alders_blood_prologue...
```

**Comment by TheLateNightFlight** [comment] 2022-02-24 23:44
I got rid of the error by changing line 360 `tmp_md5_url = page.geturl().replace('?', '.xml?')` to `tmp_md5_url = page.geturl() + ".xml";`

**Comment by sairuk** [comment] 2022-02-26 01:01
This appeared to correct itself without intervention late yesterday, if someone else can confirm for me (without patching), i will happily close this ticket off

**Comment by jturner314** [comment] 2022-02-26 23:35
Fwiw, I just experienced this issue a few minutes ago, and the fix in @TheLateNightFlight's [comment above](https://github.com/eddie3/gogrepo/issues/63#issuecomment-1050368784) worked for me.

**Comment by darkain** [comment] 2022-02-28 02:13
Same issue here on Feb 27th. Applied the line edit above, and all seems good again. Thanks :)

**Comment by DerPit** [comment] 2022-02-28 11:54
Just checked.  Also here, I **do** need the patch to get rid of the errors.
Just re-read the whole database (223 games), two of them gave the md5 error despite the patched code:
Foxtail and Hedon.

**Comment by CalAlaera** [comment] 2022-03-05 10:47
Happening for me too. All of my purchased games, without exception, were giving me the error. The patch mentioned in https://github.com/eddie3/gogrepo/issues/63#issuecomment-1050368784 **did** correct the error for me. Thanks for your work, all. :)

**Comment by sairuk** [comment] 2022-03-06 21:32
A few games were still failing to find the md5 for me with the patch, turns out gog gzip larger game info xmls and it wasn't handled, i've added support and a variation on the patch in my fork now and switched our project across to use that.

We also noted thanks to a report on our issues for RetroNAS, sync is completely broken for downloading game files with these xml errors, it'll only sync extras. Originally i'd just figured it was informational

since i like output, i've added an info message containing found md5s as well

```
21:25:06 | (  1 / 255) fetching game details for a_space_for_the_unbound_prologue...
21:25:12 | successfully found md5 f7482a8a60accbf2d00f027ad258eb1d
21:25:12 | (  2 / 255) fetching game details for absolute_drift...
21:25:18 | successfully found md5 5f5a022466dcb0bc6cc5640c997b3ec2
21:25:18 | (  3 / 255) fetching game details for against_the_moon_prologue...
21:25:24 | successfully found md5 7da3706c0407eac41112399ecd4ec111
21:25:24 | (  4 / 255) fetching game details for akalabeth_world_of_doom...
21:25:30 | successfully found md5 c9421b7f1f0bde9a17796d346008b3ad
21:25:40 | (  5 / 255) fetching game details for alders_blood_prologue...
21:25:46 | successfully found md5 849a5ad3725cf3fb06e774b53947fe72
21:25:46 | (  6 / 255) fetching game details for alone_in_the_dark_1...
21:25:52 | successfully found md5 20a86a0c70f898b3355e26bde796746e
21:25:59 | (  7 / 255) fetching game details for alone_in_the_dark_2...
21:26:06 | successfully found md5 6db6990637b15f36628c8fcb30faa2db
```

Control still has/had an issue getting one of its md5s but i dumped out my temp_md5_url and tried to browse and curl it, both were broken, i also gave it a few mins incase generation was slow on gogs end then I was going to add a retry mech, no luck

```
21:20:27 | xml parsing error occurred trying to get md5 data for setup_control_ultimate_edition_update_2_(41492)-2.bin
```

There may be more in that same boat, i'm going through a full update now

**Comment by ToxiClay** [comment] 2022-03-09 02:19
I can confirm that @TheLateNightFlight's fix isn't total. The following games still report md5 errors using his patch:
```
Cyberpunk 2077
Deus Ex: Mankind Divided
Hedon
Metro: Last Light Redux
No Man's Sky
Star Renegades
Stellaris
```

Hedon and Star Renegades confuses me, as those are not huge games.

Now, I'll try cherry-picking your commit over to my fork and see what happens.

After swapping Python 2.7.18 for 3.10.2 because I'm a dumb idiot who both was still running 2.x and can't figure out coexistence, I, too, still have two lingering MD5 errors. I'm not knowledgeable enough to debug the variable like you did, so I'll just presume my error is the same as yours.

```
Line 82: 14:47:22 | xml parsing error occurred trying to get md5 data for patch_cyberpunk_2077_Hotfix_1.5_(53778)_to_Build_3864499Change_4719897_(53890).exe
Line 465: 15:14:46 | xml parsing error occurred trying to get md5 data for setup_star_renegades_1.5.1.5_(53756)-1.bin
```

**Comment by sairuk** [comment] 2022-03-09 04:21
I have an issue with one file for Control but the md5 page wasn't available.

You _could_ add a line after [this](https://github.com/sairuk/gogrepo/blob/30047f17614cef7ec686d2dc2b6981cbf52585a3/gogrepo.py#L364) to print out the `tmp_md5_url` to the console and then try the links in your browser see if they are valid (they include your token iirc, so don't drop em anywhere) xml, then if so, check headers in developer tools to try and identify if they are perhaps using deflate and not gzip etc

I do not own either of those games to test with unfortunately

**Comment by ToxiClay** [comment] 2022-03-09 09:45
Pulling up one of the successful URLs in the browser gives me this:
```
<file name="setup_star_renegades_1.5.1.5_(53756).exe" available="1" notavailablemsg="" md5="19e753b6e0959ed69842446fce929328" chunks="1" timestamp="2022-02-17 21:15:30" total_size="943168">
<chunk id="0" from="0" to="943167" method="md5">19e753b6e0959ed69842446fce929328</chunk>
</file>
```

and here's the curl output:

```
C:\Users\Omega>curl https://gog-cdn-lumen.secure2.footprint.net/token=[[REDACTED]]/setup_star_renegades_1.5.1.5_%2853756%29.exe.xml -o test_success.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   217  100   217    0     0   2040      0 --:--:-- --:--:-- --:--:--  2066

C:\Users\Omega>
```

Interestingly, trying to open the output file in Notepad++ gives me gibberish.

The curl for the failing MD5 just sits and spins. It's been spinning for three and a half minutes, and I bet if I let it sit and spin while I go to work, it'll just spin for h o u r s.

**Comment by Sargon-Aelther** [comment] 2022-06-17 13:51
I seem to be getting this for nearly every game. Do I need to edit the code as some comments here suggested or is GOG suffering heavy traffic or something?

**Comment by eddie3** [comment] 2022-07-19 01:33
Thanks all. GOG changed the URLs for where MD5 XML data is stored. I've pushed a fix for this.

**Closed by eddie3** 2022-07-19 01:33 UTC
